language: python

sudo: required
services:
  - docker

cache:
  - pip

before_install:
  - docker-compose -f ./.travis/docker-compose-travis.yml up -d

install:
  - docker exec -t journals_testing bash -c 'cd /edx/app/journals/journals/ && make requirements'

script:
  - docker exec -it journals_testing bash -c 'cd /edx/app/journals/journals/ && xvfb-run make validate'
